assets_model("ttg/ImmuneEnchant", "lk_ttg_immune_enchant")
assets_model("ttg/EnchantDark", "lk_ttg_e_dark")
assets_model("ttg/EnchantFire", "lk_ttg_e_fire")
assets_model("ttg/EnchantGrass", "lk_ttg_e_grass")
assets_model("ttg/EnchantIce", "lk_ttg_e_ice")
assets_model("ttg/EnchantLight", "lk_ttg_e_light")
assets_model("ttg/EnchantPoison", "lk_ttg_e_poison")
assets_model("ttg/EnchantRock", "lk_ttg_e_rock")
assets_model("ttg/EnchantThunder", "lk_ttg_e_thunder")
assets_model("ttg/EnchantWater", "lk_ttg_e_water")
assets_model("ttg/EnchantWind", "lk_ttg_e_wind")
assets_model("ttg/EnchantSteel", "lk_ttg_e_steel")

assets_model("ttg/WordOrange+", "lk_word_+")
assets_model("ttg/WordOrange-", "lk_word_-")
assets_model("ttg/WordOrange0", "lk_word_0")
assets_model("ttg/WordOrange1", "lk_word_1")
assets_model("ttg/WordOrange2", "lk_word_2")
assets_model("ttg/WordOrange3", "lk_word_3")
assets_model("ttg/WordOrange4", "lk_word_4")
assets_model("ttg/WordOrange5", "lk_word_5")
assets_model("ttg/WordOrange6", "lk_word_6")
assets_model("ttg/WordOrange7", "lk_word_7")
assets_model("ttg/WordOrange8", "lk_word_8")
assets_model("ttg/WordOrange9", "lk_word_9")
assets_model("ttg/WordOrangeCrit1", "lk_word_crit")

assets_model("interface/BossAlert") -- 指示器[条]100*750
assets_model("interface/BossAlertRing") -- 指示器[圆]160
assets_model("interface/BossAlertSquare") -- 指示器[正方]160