-- 漂浮字符
mtg.char("default", "0", "lk_word_0", 1.9)
mtg.char("default", "1", "lk_word_1", 1.8)
mtg.char("default", "2", "lk_word_2", 1.8)
mtg.char("default", "3", "lk_word_3", 1.8)
mtg.char("default", "4", "lk_word_4", 1.8)
mtg.char("default", "5", "lk_word_5", 1.8)
mtg.char("default", "6", "lk_word_6", 1.8)
mtg.char("default", "7", "lk_word_7", 1.8)
mtg.char("default", "8", "lk_word_8", 1.8)
mtg.char("default", "9", "lk_word_9", 1.8)
mtg.char("default", "+", "lk_word_+", 1.7)
mtg.char("default", "-", "lk_word_-", 1.7)
mtg.char("default", "C", "lk_word_crit", 2.5)